/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Slate(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/main/models/Slate.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
        position={[-20.26, 41.37, 0]}
        scale={[0.85, 0.86, 0.15]}
      />
    </group>
  );
}

useGLTF.preload("/main/models/Slate.gltf");
